### ISSUE TITLE
Ticket list & Task is not Rendering properly

### ISSUE THREAD

**Issue by mdkaleel** [Project-Pier/ProjectPier-Theme-Marine#1] opened 2015-01-19 07:46 UTC
@Engelbert 

Ticket list & Task is not Rendering properly

Browser: Chrome,Mozilla
Resolution : 1366 x 768

![3de22a80-9a32-11e4-82c9-06a924c4686a](https://cloud.githubusercontent.com/assets/10484071/5797222/28c4b434-9fc7-11e4-8ce4-b2f4ba067fa8.png)

**Comment by Engelbert** [comment] 2015-01-19 19:45
@mdkaleel : I had a quick look at this issue and found out that this behaviour is caused by a css rule in the [rewrite.css](https://github.com/Project-Pier/ProjectPier-Theme-Marine/blob/master/public/assets/themes/marine/stylesheets/general/rewrites.css) file on rule no. 131.

The file is located @ `public/assets/themes/marine/stylesheets/general/rewrites.css`
Changing:

``` css
table  {
 border: 1px solid #CCCCCC;
 border-collapse: collapse;
 width: inherit;
}
```

to

``` css
table  {
 border: 1px solid #CCCCCC;
 border-collapse: collapse;
 /* width: inherit; */
}
```

solves the issue for me. If you can confirm this, I shall make a pull request that solves this issue.

Thanks for your patience and willingness to report bugs! It really helps mate! :+1:

**Comment by mdkaleel** [comment] 2015-01-20 12:12
@Engelbert 

Yes its Fixed. Thanks

**Comment by Engelbert** [comment] 2015-01-20 15:08
**Reopened**
 so I can close it with a commit :smile:

**Closed as completed** 2015-01-20 20:36 UTC
